### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [Davarco/Divertio#3]
Speaking of Open Source and contributions: Could you please specify what license this app is under? I've checked Readme and repo, even looked into some source files, but could find no hint.

Thanks in advance!

**Comment by Davarco** [comment]
Hi!
Sorry I haven't been able to respond; I've been sort of busy on vacation these last few weeks. 
The lack of a license was an oversight, I just added it.

Cheers!
Davarco

**Comment by IzzySoft** [comment]
Thanks a lot! Already thought it must have been overseen – nice to have it visible now, and being an open one!
